# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 701670fbcc62cbba30b1c6722bcf20a22284b23be29d38f2fa0bf8abf2ecc134061094851547d7dc6b6cf2ea91eb206a346fac3482dd3a2dc2ff6a10b48320c6

test:
  secret_key_base: e7552c9eeb5aeb247cb4719b07fe799c656ec01e567b994a6a05cc8a3c638c631fc26de9692561a00b1c46dc4608759c438d09525770adaf5bd886899efb2f8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
